-- RememberMe table
create table persistent_logins (username varchar(64) not null,
                                series varchar(64) primary key,
                                token varchar(64) not null,
                                last_used timestamp not null);

-->>> JdbcUserDetailsManager tables
create table users(
                      username varchar(50) not null primary key,
                      password varchar(500) not null,
                      enabled boolean not null
);
create table authorities (
                             username varchar(50) not null,
                             authority varchar(50) not null,
                             constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);
create table groups (
                        id bigint generated by default as identity(start with 1) primary key,
                        group_name varchar(50) not null
);
create table group_authorities (
                                   group_id bigint not null,
                                   authority varchar(50) not null,
                                   constraint fk_group_authorities_group foreign key(group_id) references groups(id)
);
create table group_members (
                               id bigint generated by default as identity(start with 1) primary key,
                               username varchar(50) not null,
                               group_id bigint not null,
                               constraint fk_group_members_group foreign key(group_id) references groups(id)
);
--<<< JdbcUserDetailsManager tables

-- Добавление пользователей
insert into users (username, password, enabled) VALUES ('user', '{bcrypt}$2y$10$k2InywsyrLMccUKw1ZeFV.Jv9ufMSGzO334UtltjphLXnOmhz0XMK', true);
insert into users (username, password, enabled) VALUES ('admin', '{bcrypt}$2y$10$InH1CU/hrcrprj.vp4Rs1uwB/SB9bbBhEmrpxFK6/ivvH2aj37rz.', true);
insert into authorities (username, authority) VALUES ('user', 'ROLE_USER');
insert into authorities (username, authority) VALUES ('admin', 'ROLE_ADMIN');